# Gunakan image Python slim sebagai base
FROM python:3.10-slim

# Tetapkan direktori kerja di dalam container
WORKDIR /app

# Salin semua file proyek ke dalam container
COPY . /app

# Install semua dependensi Python
RUN pip install --no-cache-dir -r requirements.txt

# Expose port untuk aplikasi Flask
EXPOSE 8080

# Perintah untuk menjalankan aplikasi
CMD ["python", "app.py"]
